#snippets_dir: changelog.d

# Categories must be listed in descending order of precedence for determining
# what category to apply to a PR with multiple labels.
# The category names must align with the categories in changelog.d/scriv.ini
categories:
  - name: 💥 Breaking Changes
    bump: minor
    label: semver-major
  - name: 🚀 Enhancements and New Features
    bump: minor
    label: semver-minor
  - name: 🐛 Bug Fixes
    label: semver-patch
  - name: 🔩 Dependencies
    label: semver-dependencies
  - name: 📝 Documentation
    label: semver-documentation
  - name: 🏠 Internal
    label: semver-internal
  - name: 🏎 Performance
    label: semver-performance
  - name: 🧪 Tests
    label: semver-tests
