name: Add changelog.d snippet

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  add:
    runs-on: ubuntu-latest
    if: >
      github.repository == 'datalad/temp-release-devel'
        && contains(github.event.pull_request.labels.*.name, 'CHANGELOG-missing')
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '^3.7'

      - name: Install Python dependencies
        run: python -m pip install --upgrade requests

      - name: Generate changelog.d snippet
        run: |
          python3 tools/ci/mkchlog-snippet.py \
            ${{ github.repository_owner }} \
            ${{ github.event.repository.name }} \
            ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        run: |
          git add changelog.d
          if ! git diff --quiet --cached
          then git commit -m '[skip ci] Autogenerate changelog.d snippet for pull request'
               git push origin HEAD:${{ github.head_ref }}
          else echo "No changes to commit"
          fi

      - name: Remove CHANGELOG-missing label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: CHANGELOG-missing

# vim:set et sts=2:
