name: Auto-release on PR merge

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  auto-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: datalad/release-action/release@init
        with:
          pre-tag: |
            echo 'This is the pre-tag step.'
            env

# vim:set sts=2:
